version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pvz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pvz"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pvz-network

  app:
    build: .
    ports:
      - "8080:8080"  # HTTP API
      - "3000:3000"  # gRPC
      - "9000:9000"  # Metrics
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: pvz
      DB_SSLMODE: disable
      JWT_SECRET: your-secret-key-here
    networks:
      - pvz-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pvz-network:
    driver: bridge